### ISSUE TITLE
Create first character

### ISSUE THREAD

**Issue by joris-lefondeur** [Group-2-SEP-2022/PokeProf#2]
# Description
Make a character, the player that can move around with necessary features.
## Tasks List
- [x] Make the player with proper walking movement.
- [x] Make the main camera follow the player.
- [x] Make collision physics & rigid body movement.
