### ISSUE TITLE
Create the first room

### ISSUE THREAD

**Issue by joris-lefondeur** [Group-2-SEP-2022/PokeProf#3]
# Description
This issue aims to create an "background" where the character of the player and the NPC can walk around. It is the settings and the environment of the characters' activities.
## Progress
- [x] Create a ground layer where the player can walk around.
- [x] Sorts layers.
- [x] Add collision physics and rigid body movement of the player character #2

**Comment by yinghan-ling** [comment]
# Description
This issue aims to create an "background" where the character of the player and the NPC can walk around. It is the settings and the environment of the characters' activities.
## Tasks List
- [ ] Create a ground layer where the player can walk around.
- [ ] Sorts layers.
- [ ] Add collision physics and rigid body movement of the player character #2
